# -*- coding: utf-8 -*-
"""ML_HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IyooRdP2T6KsfEJCBWrdklWaql3WU_4j
"""

import random
numNeedles = 1000000
piGuess=0.0
#4/3 pi r^3
def throwNeedles(numNeedles):
  inCircle = 0
  for Needles in range(1,numNeedles+1):
    x = random.uniform(0,1)
    y = random.uniform(0,1)
    z = random.uniform(0,1)
    if (x*x+y*y+z*z) <= 1:
      inCircle += 1
  return (inCircle/numNeedles)
piGuess = throwNeedles(numNeedles)
print('Est = ',piGuess)

import random
import matplotlib.pyplot as plt
import pandas as pd
w2 = 2.0
w1 = 0.5
w0 = 0.3
num_sample = 30
data_set = []
x_set = []
y_set = []
for i in range(0,num_sample):
  x = random.uniform(0,1)
  r=w2*x*x+w1*x+w0+random.gauss(0,0.1)
  #print('x',round(x,3),'r',round(r,3))
  x_set.append(round(x,3))
  y_set.append(round(r,3))
  data_set.append([round(x,3),round(r,3)])
plt.scatter(x_set,y_set)
plt.xlabel('x')
plt.ylabel('r')
data = pd.DataFrame(data_set)
data.to_excel('sample_data.xlsx', sheet_name='sheet1', index=False)

"""# 新增區段"""

data

import random
numNeedles = 1000000
piGuess=0.0

def throwNeedles(numNeedles):
  inCircle = 0
  for Needles in range(1,numNeedles+1):
    x = random.uniform(0,1)
    y = random.uniform(0,1)
    if (x*x) >= y:
      inCircle += 1
  return (inCircle/numNeedles)
piGuess = throwNeedles(numNeedles)
print('Est = ',piGuess)